### ISSUE TITLE
How to use the `Key` class?

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#134]
Apologies if I'm missing something obvious, here is where I am:
```
>>> from pycoin.key import Key
>>> 
>>> Key(secret_exponent=44046069343753645157816417760271632919159883697415896998605448368092956521898)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pycoin/key/Key.py", line 221, in __repr__
    r = self.public_copy().as_text()
  File "/usr/lib/python2.7/site-packages/pycoin/key/Key.py", line 198, in public_copy
    is_compressed=self._is_compressed, netcode=self._netcode)
AttributeError: 'Key' object has no attribute '_is_compressed'
>>> 
>>> Key.from_text('15S315coWY8XUD6i2dxjyxwiQ1dde3cFuB')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pycoin/key/Key.py", line 221, in __repr__
    r = self.public_copy().as_text()
  File "/usr/lib/python2.7/site-packages/pycoin/key/Key.py", line 190, in as_text
    if pp:
NameError: global name 'pp' is not defined
```
Using `ku` and `tx` from the command line works great but I want to load in xpub and xpriv addresses to generate subkeys inside the python console (2.7).

Please help :)

**Comment by derrend** [comment]
I figured it out
```
>>> from pycoin.key.Key import Key
>>> x = Key.from_text('xpub661MyMwAqRbcEzpvZxHiBBstxbjg5Fg4V1ETBiGJsAPTBjVP2stMdX9mmgXhVch36ZgrttKbBssBGxjdxDSw5Y2WJbtJMUhKFYdi6fPCo4H')
>>> x
<xpub661MyMwAqRbcEzpvZxHiBBstxbjg5Fg4V1ETBiGJsAPTBjVP2stMdX9mmgXhVch36ZgrttKbBssBGxjdxDSw5Y2WJbtJMUhKFYdi6fPCo4H>
>>> x.address
u'1223r8ynAZCR13bY61PBAR3sCbQYKo8BXh'
```

**Comment by richardkiss** [comment]
Glad you got it worked out. Incidentally, you were using Key correctly in the first example... I could not reproduce the error you found.

**Comment by derrend** [comment]
In the first example I was one `.Key` short whilst importing it seems :)
