### ISSUE TITLE
Why is `spendables_for_address` asking me for two arguments?

### ISSUE THREAD

**Issue by derrend** [richardkiss/pycoin#193]
```
>>> spendables = spendables_for_address('17mumjdTWHsRWTubn7rQ8j7h62qHV3VVBm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: spendables_for_address() takes at least 2 arguments (1 given)
```

**Comment by richardkiss** [comment]
It wants a netcode so it knows what network to query. For bitcoin, use "BTC". It could probably make an intelligent guess, based on the address, but it currently doesn't. See also <https://github.com/richardkiss/pycoin/blob/master/pycoin/services/providers.py>

**Comment by derrend** [comment]
I tried that too but still no luck.
```
>>> spendables_for_address('17mumjdTWHsRWTubn7rQ8j7h62qHV3VVBm', netcode="BTC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: spendables_for_address() got an unexpected keyword argument 'netcode'
```

**Comment by derrend** [comment]
That fixed it, thanks.
