### ISSUE TITLE
IndexError: list index out of range when trying to create tx

### ISSUE THREAD

**Issue by jooray** [richardkiss/pycoin#194]
I want to spend all outputs to a private key (I have a WIF). I think this bug is introduced in 0.7.

Code:

``` python
from pycoin.key import Key

from pycoin.key.validate import is_address_valid, is_wif_valid
from pycoin.services import spendables_for_address
from pycoin.tx.tx_utils import create_signed_tx

src_address = "1src..."
wif = "L3Zxxxxxxxxxxxxxxxxxxxx"
dst_address = "1dest..."


spendables = spendables_for_address(src_address, "BTC")
for spendable in spendables:
    print(spendable)

key = Key.from_text(wif)
if src_address not in (key.address(use_uncompressed=False), key.address(use_uncompressed=True)):
    print("** WIF doesn't correspond to %s" % src_address)
print("The secret exponent is %d" % key.secret_exponent())


tx = create_signed_tx(spendables, payables=[dst_address], wifs=[wif])

print("here is the signed output transaction")
print(tx.as_hex())
```

I get a list of spendables with some mbtc, it prints the secret exponent and then only this:

```
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 66, in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 66, in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
```

Internals of Bitcoin VM is too much for me, but I suppose this should work. If nothing else, a better error  message should be reported.

If this works, I will create a pull request for this example. 

My shell variables: 

``` bash
PYCOIN_BTC_PROVIDERS='blockr.io blockchain.info blockr.io blockexplorer.com'
PYCOIN_CACHE_DIR=/Users/juraj/.pycoin_cache
```

**Comment by jooray** [comment]
Simplified test case:

```bash
python3 tx.py d7695f9952c38716d1e1ff14ade323bbc6469972b9831b8ca86f58de073b161a/0/76a9146737de376fc3549ef551fdb061eec70f6c7f99de88ac/69200 169SjjMArxBCSXnUFnbQadkoMenajcri8o -o tx.bin
```

```
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 66, in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.5/site-packages/pycoin/tx/script/vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
all incoming transaction values validated
```

**Comment by jooray** [comment]
Seems to be an issue with Python 3.5

Works with Python 2.7

**Comment by xuhcc** [comment]
I see this error too when trying to sign a transaction that contains both P2PKH and P2SH inputs. However, it seems that valid signatures are produced (my transaction was successfuly included in block).
*pycoin 0.70, python 3.5.1*

**Comment by januszdotnl** [comment]
Hi, yes I'm having the same issue although like @xuhcc I do get a valid signature. I am using Python 3.4.4 by the way:

`root@dev:/utils# python test2.py

script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/vm.py", line 66, in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/vm.py", line 66, in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/microcode.py", line 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.4/site-packages/pycoin/tx/script/vm.py", line 68, in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
here is the signed output transaction
0100000001b3859c80e7f42356b5c1808923bd5fb02bbb7a4be02145125191bb89b18df401000000006b483045022100c371adb4864f643dbacdeb13ce5498df8b4bdc858913b044ab8790298c1f9e9002203b02c73a044d40e8bb7ec8a74b405a92f8dd9a97c778ea9c8887da62f08zdfca012102dee0c18c9535e3ccf6027124331b2a4b224dec0536c5967fcc31d8d93f00d3d7ffffffff01f0ca052a010000001976a91485535d3582e75b7098f76eddebe48238a1a9247f88ac00000000
`

**Comment by richardkiss** [comment]
This is due to debug logging code that is produced when the script fails (the transaction is tested for validity so we don't destroy an already signed input). You can ignore it for now. I plan to remove these confusing messages.

**Comment by richardkiss** [comment]
This logging is now gone.
