### ISSUE TITLE
ValueError: bad flag in segwit after upgrade to 0.76

### ISSUE THREAD

**Issue by F483** [richardkiss/pycoin#224]
I upgraded from 0.70 to 0.76 and while I managed to fix most of my code that broke I can only seem to 'fix' this by disabling segwit ```Tx.ALLOW_SEGWIT = False```, which seems like something I would not like to be doing.

The transaction is a bit odd, but I would argue it should be a bug as bitcoind handles it just fine.

## Code:

```
(env)f483@f483-laptop ~/dev/upstream/pycoin $ cat example.py 
from pycoin.tx import Tx

RAWTX = (
    "010000000002145fea0b000000001976a9144838d8b3588c4c7ba7c1d06f866e9b3739c"
    "6303788ac0000000000000000346a32544553540000000a000000000000000100000000"
    "05f5e1000000000000000000000000000bebc2000032000000000000271000000000"
)

Tx.from_hex(RAWTX)
```

## Error:

```
(env)f483@f483-laptop ~/dev/upstream/pycoin $ python example.py 
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    Tx.from_hex(RAWTX)
  File "/home/f483/dev/upstream/pycoin/pycoin/tx/Tx.py", line 139, in from_hex
    return cls.from_bin(h2b(hex_string))
  File "/home/f483/dev/upstream/pycoin/pycoin/tx/Tx.py", line 128, in from_bin
    tx = cls.parse(f)
  File "/home/f483/dev/upstream/pycoin/pycoin/tx/Tx.py", line 103, in parse
    raise ValueError("bad flag in segwit")
ValueError: bad flag in segwit
```

## setup:

```
(env)f483@f483-laptop ~/dev/upstream/pycoin $ pip freeze
pycoin==0.76
wheel==0.29.0

```

## Decoded transaction:

```
f483@f483-laptop ~/dev/micropayments/picopayments-hub $ bitcoin-cli --rpcuser=bitcoinrpcuser --rpcpassword=bitcoinrpcpass --rpcport=18332 decoderawtransaction 010000000002145fea0b000000001976a9144838d8b3588c4c7ba7c1d06f866e9b3739c6303788ac0000000000000000346a32544553540000000a00000000000000010000000005f5e1000000000000000000000000000bebc2000032000000000000271000000000
{
  "txid": "ba73e7cd621a8959517ff53f2bfda4228f9761a58f5b67a76c1c2e6fd7ebc35b",
  "size": 105,
  "version": 1,
  "locktime": 0,
  "vin": [
  ],
  "vout": [
    {
      "value": 1.99909140,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 4838d8b3588c4c7ba7c1d06f866e9b3739c63037 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a9144838d8b3588c4c7ba7c1d06f866e9b3739c6303788ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mn6q3dS2EnDUx3bmyWc6D4szJNVGtaR7zc"
        ]
      }
    }, 
    {
      "value": 0.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_RETURN 544553540000000a00000000000000010000000005f5e1000000000000000000000000000bebc20000320000000000002710",
        "hex": "6a32544553540000000a00000000000000010000000005f5e1000000000000000000000000000bebc20000320000000000002710",
        "type": "nulldata"
      }
    }
  ]
}
```

**Comment by richardkiss** [comment]
You're right, https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki#Serialization suggests this flag value need only be non-zero, not be 1. I will fix this.

**Comment by F483** [comment]
Thanks

**Comment by richardkiss** [comment]
Fixed in 63fe190598a5e47ec32c84f810c704c4157b36fa.

**Comment by F483** [comment]
Thanks!

**Comment by richardkiss** [comment]
Test case added in cb1f84e064d986207179311d1c34e2a5c40e6ea8
