### ISSUE TITLE
block terminal command fails

### ISSUE THREAD

**Issue by mlda065** [richardkiss/pycoin#268]
# Steps to reproduce

1. Install bitcoind
2. Run bitcoind, to download the blockchain
3. Install pycoin 
   * python 2.7 or 3.6, either one gives the same result
   * straight from git, or normal `pip install pycoin`. Either one gives the same result

```
python3 -m virtualenv --python=/usr/bin/python3.6 env
. ./env/bin/activate
pip install git+https://github.com/richardkiss/pycoin.git
```
4. Run `block blk00708.dat` where `blk00708.dat` is a random block in the blockchain

# Expected result

The terminal prints out info about that .dat file

# Actual result

```
(env) matthew@kira:~/Documents/Projects/bitcoin_volume/pycoin$ block blocks/blk00708.dat 
Traceback (most recent call last):
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/bin/block", line 11, in <module>
    load_entry_point('pycoin==0.80', 'console_scripts', 'block')()
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/cmds/block.py", line 46, in main
    block(args, parser)
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/cmds/block.py", line 38, in block
    block = Block.parse(f)
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/block.py", line 35, in parse
    txs = block._parse_transactions(f, count, include_offsets=include_offsets)
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/block.py", line 86, in _parse_transactions
    tx = class_.Tx.parse(f)
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/tx/Tx.py", line 112, in parse
    txs_in.append(class_.TxIn.parse(f))
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/tx/TxIn.py", line 62, in parse
    return self(*parse_struct("#LSL", f))
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/serialize/streamer.py", line 39, in parse_struct
    l.append(self.parse_lookup[c](f))
  File "/home/matthew/Documents/Projects/bitcoin_volume/pycoin/env/lib/python3.6/site-packages/pycoin/serialize/bitcoin_streamer.py", line 45, in <lambda>
    "L": (lambda f: struct.unpack("<L", f.read(4))[0], lambda f, v: f.write(struct.pack("<L", v))),
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by richardkiss** [comment]
This tool actually assumes that the file is a streamed block. An easy way to get the streamed block is with the get_block tool in pycoinnet. See https://github.com/richardkiss/pycoinnet/blob/remix/pycoinnet/cmds/get_block.py

There are tools to parse bitcoind's .dat file format at https://github.com/richardkiss/pycoin/blob/master/pycoin/tools/bitcoind_disk.py. They are neither documented nor tested, so may suffer from bitrot.
