### ISSUE TITLE
Blockcypher txs/push gives 404

### ISSUE THREAD

**Issue by charlieb** [richardkiss/pycoin#276]
Blockcypher txs/push gives 404, suspect json encoding. Will test later

Error from https://github.com/charlieb/dashnotes 
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "./sendfunds.py", line 231, in send
    txid = send_funds(self.address, addr_amts, self.privkey)
  File "./sendfunds.py", line 45, in send_funds
    spendables = bc.spendables_for_address(from_addr)
  File "/usr/lib/python3.6/site-packages/pycoin/services/blockcypher.py", line 35, in spendables_for_address
    result = json.loads(urlopen(url).read().decode("utf8"))
  File "/usr/lib/python3.6/site-packages/pycoin/services/agent.py", line 17, in urlopen
    return request.urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by charlieb** [comment]
Confirmed same error on Windows so it's not a Linux environment issue.

**Comment by richardkiss** [comment]
Maybe this endpoint needs a POST instead of a GET?

**Comment by shayanb** [comment]
@richardkiss yes it should be a POST request

**Comment by charlieb** [comment]
https://www.blockcypher.com/dev/dash/?shell#push-raw-transaction-endpoint

Yes this says POST.

**Comment by charlieb** [comment]
Sorry wrong endpoint. The addr endpoint needs a GET.

https://www.blockcypher.com/dev/dash/?shell#address-endpoint

**Comment by charlieb** [comment]
The original post here was the wrong stack trace and thus my extensive confusion. I will make a new issue with the correct message, which is much clearer.
