### ISSUE TITLE
KeyError: 'wallet_key'

### ISSUE THREAD

**Issue by kenorb** [richardkiss/pycoin#290]
```
$ ku -w 1
Traceback (most recent call last):
  File "/usr/local/bin/ku", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pycoin/cmds/ku.py", line 353, in main
    ku(args, parser)
  File "/usr/local/lib/python3.6/site-packages/pycoin/cmds/ku.py", line 347, in ku
    generate_output(args, output_dict, output_order)
  File "/usr/local/lib/python3.6/site-packages/pycoin/cmds/ku.py", line 312, in generate_output
    print(output_dict["wallet_key"])
KeyError: 'wallet_key'
$ ku --help | grep -- -w
usage: ku [-h] [-w] [-W] [-a] [-u] [-P] [-j] [-s SUBKEY]
  -w, --wallet          show just Bitcoin wallet key
  -W, --wif             show just Bitcoin WIF
$ pip list | grep ^pycoin
pycoin               0.80  
```

Related: GH-129

Is it the expected behaviour?

**Comment by richardkiss** [comment]
Try `ku -W 1` instead.
