### ISSUE TITLE
can't parse 3D: add support for script format

### ISSUE THREAD

**Issue by kenorb** [richardkiss/pycoin#294]
```
$ ku 3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r
can't parse 3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r
```

But it resolves at [blockchain.info](https://blockchain.info/address/3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r).

**Comment by yannik995** [comment]
I have the same failure:

```
Traceback (most recent call last):
  File "./test.py", line 25, in <module>
    key = Key.from_text(line)
  File "/home/XXX/.local/lib/python3.5/site-packages/pycoin/key/Key.py", line 106, in from_text
    raise EncodingError("unknown text: %s" % text)
pycoin.encoding.EncodingError: unknown text: 3D2oetdNuZUqQHPJmcMDDHYoqkyNVsFk9r
```

**Comment by richardkiss** [comment]
This works now.
