### ISSUE TITLE
AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: BN_init

### ISSUE THREAD

**Issue by fredbeltrao** [richardkiss/pycoin#311]
`uname -a`
Linux marte 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

`python -V`
Python 3.6.6

If I remove the try/except from env/lib/python3.6/site-packages/pycoin/ecdsa/native/library.py
```
try:
    NATIVE_LIBRARY = load_library()
except:
    NATIVE_LIBRARY = None
```

I get the following error:
```
Connected to pydev debugger (build 182.4505.26)
Traceback (most recent call last):
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/85/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/85/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fred/git/address/vanity.py", line 2, in <module>
    from pycoin.key import Key
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/key/__init__.py", line 1, in <module>
    from .Key import Key  # noqa
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/key/Key.py", line 1, in <module>
    from pycoin import ecdsa
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/__init__.py", line 2, in <module>
    from .ecdsa import (  # noqa
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/ecdsa.py", line 31, in <module>
    from . import ellipticcurve, numbertheory
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/ellipticcurve.py", line 35, in <module>
    from . import numbertheory
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/numbertheory.py", line 2, in <module>
    from .native.library import NATIVE_LIBRARY
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/native/library.py", line 105, in <module>
    NATIVE_LIBRARY = load_library()
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/native/library.py", line 66, in load_library
    set_api(library, BIGNUM_API)
  File "/home/fred/git/address/env/lib/python3.6/site-packages/pycoin/ecdsa/native/library.py", line 14, in set_api
    f = getattr(library, f_name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: BN_init

```
With try/except, key generation is 36x slower.

**Comment by richardkiss** [comment]
I think what's happened is that `BN_init` has been removed from the bignum library. It's never called in pycoin anyway, so I think removing it is without risk. You want to try that?

**Comment by richardkiss** [comment]
Actually, it looks like that has already been done in master. If you're brave, try the master branch. You may have to do some refactoring.

**Comment by fredbeltrao** [comment]
That was the quickest reply I've ever seen! Thank you for that!
I'm using pycoin 0.80 in a virtualenv setup. How can I put master branch on such scenario?

**Comment by fredbeltrao** [comment]
> I think what's happened is that `BN_init` has been removed from the bignum library. It's never called in pycoin anyway, so I think removing it is without risk. You want to try that?

It works great just removing BN_init! Thanks again!

**Comment by richardkiss** [comment]
You got lucky... sometimes these reports linger for months!!

Do a `git clone` of pycoin and do `pip install . --upgrade` while in the directory with `setup.py` and it will go into your virtualenv.
