### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by justinmoon** [richardkiss/pycoin#336]
When I install pycoin using pip:

```
>>> from pycoin.symbols.btc import network
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pycoin.symbols'
```

```
>>> from pycoin.networks.registry import network_for_netcode
>>> network = network_for_netcode("BTC")
>>> key = network.keys.private(secret_exponent=1)  # this is a terrible key because it's very guessable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Network' object has no attribute 'keys'
```

Encountered this same problem on an arch linux development machine and a ubuntu VPS.

**Comment by richardkiss** [comment]
Try the master branch (which will be the as-yet-unreleased v0.9).
