### ISSUE TITLE
spendables_for_address("XTN") Error

### ISSUE THREAD

**Issue by BruceChar** [richardkiss/pycoin#348]
Traceback (most recent call last):
  File "E:/Python/TokenTrade/web3Test/app/mock/cb_api.py", line 49, in <module>
    print(bp.spendables_for_address("mxN7UQCwdEJ9Ctph6pHmkJHifCCuwquejf"))
  File "E:\Python\TokenTrade\web3Test\app\lib\site-packages\pycoin\services\blockchain_info.py", line 47, in spendables_for_address
    r = json.loads(urlopen(URL).read().decode("utf8"))
  File "E:\Python\TokenTrade\web3Test\app\lib\site-packages\pycoin\services\agent.py", line 17, in urlopen
    return request.urlopen(req)
  File "D:\Python3.7.0\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python3.7.0\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\Python3.7.0\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python3.7.0\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\Python3.7.0\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Python3.7.0\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

It looks like the "testnet.blockchain.info" site stop working!
@richardkiss  Is there a fix or replace solution for testnet?

**Comment by richardkiss** [comment]
Not that I'm aware of, but pull requests are most welcome.
