### ISSUE TITLE
Bitcoin Testnet Encoding

### ISSUE THREAD

**Issue by shayanb** [richardkiss/pycoin#87]
I've been working to make pycoin work with Bitcoin Testnet Multisig, I added Blockr.io testnet API to get the spendables, but the chain of code getting there has not yet been fixed.

This is the code I used to get the testnet spendables:
```
def spendables_for_addr(address, netcode='BTC'):
    """
    Return a list of Spendable objects for the
    given bitcoin address.
    """
    from pycoin.convention import btc_to_satoshi
    from pycoin.tx import Tx, Spendable
    from urllib2 import urlopen

    #Support for bitcoin testnet api in Blockr.io
    if netcode == "XTN":
        URL = "http://tbtc.blockr.io/api/v1/address/unspent/%s" % address
    if netcode == "BTC":
        URL = "http://btc.blockr.io/api/v1/address/unspent/%s" % address
    r = json.loads(urlopen(URL).read().decode("utf8"))
    spendables = []
    for u in r.get("data", {}).get("unspent", []):
        coin_value = btc_to_satoshi(u.get("amount"))
        script = h2b(u.get("script"))
        previous_hash = h2b_rev(u.get("tx"))
        previous_index = u.get("n")
        spendables.append(Spendable(coin_value, script, previous_hash, previous_index))
    return spendables
```

Now the problem is with the WIF encoding, I guess the solution would be to pass netcode all along the functions to reach https://github.com/richardkiss/pycoin/blob/master/pycoin/encoding.py#L187 or probably to LazySecretExponentDB(...)

Here is the encoding error:
```
    tx_final =  tx_utils.create_signed_tx([spendables_for_addr(address, netcode=temp_netcode)[0]], [testnet_address], wifs=([key.wif() for key in keys[:M]]), fee=1000, netcode=temp_netcode, p2sh_lookup=p2sh_lookup)
  File "../pycoin/pycoin/tx/tx_utils.py", line 202, in create_signed_tx
    sign_tx(tx, wifs=wifs, secret_exponent_db=secret_exponent_db, **kwargs)
  File "../pycoin/pycoin/tx/tx_utils.py", line 170, in sign_tx
    tx.sign(LazySecretExponentDB(wifs, secret_exponent_db), **kwargs)
  File "../pycoin/pycoin/tx/Tx.py", line 374, in sign
    hash160_lookup, idx, self.unspents[idx].script, hash_type=hash_type, **kwargs)
  File "../pycoin/pycoin/tx/Tx.py", line 249, in sign_tx_in
    existing_script=self.txs_in[tx_in_idx].script, **kwargs)
  File "../pycoin/pycoin/tx/pay_to/ScriptPayToScript.py", line 41, in solve
    underlying_solution = script_obj.solve(**kwargs)
  File "../pycoin/pycoin/tx/pay_to/ScriptMultisig.py", line 118, in solve
    result = db.get(hash160)
  File "../pycoin/pycoin/tx/tx_utils.py", line 29, in get
    secret_exponent = wif_to_secret_exponent(wif)
  File "../pycoin/pycoin/encoding.py", line 203, in wif_to_secret_exponent
    return wif_to_tuple_of_secret_exponent_compressed(wif, allowable_wif_prefixes=allowable_wif_prefixes, netcode = netcode)[0]
  File "../pycoin/pycoin/encoding.py", line 197, in wif_to_tuple_of_secret_exponent_compressed
    raise EncodingError("unexpected first byte of WIF %s" % wif)
pycoin.encoding.EncodingError: unexpected first byte of WIF cVVNL17sdMoGQasdSdj4jGJHTaz6JohgmS2AahhhatQwRFn
```

The workaround for now is to comment these two lines https://github.com/richardkiss/pycoin/blob/master/pycoin/encoding.py#L195-L196:

```
    if actual_prefix not in allowable_wif_prefixes:
        raise EncodingError("unexpected first byte of WIF %s" % wif)
```
or add **[b'\xef']** to allowable_wif_prefixes.

**Comment by johtso** [comment]
testnet support would be fantastic.
I'm currently getting:
```
❯ tx msrHvAWFioQ3JCGYgur5dH4g459ayAxVwR -n T                                                     ⏎ ◼
warning: insufficient inputs for outputs
warning: transaction has no inputs
warning: transaction fees recommendations casually calculated and estimates may be incorrect
warning: transaction fee lower than (casually calculated) expected value of 0.1 mBTC, transaction might not propogate
Version:  1  tx hash 493d562a4f17118b1251cc08cfdfa9aae6023b4e0a9a35901f2c20d6f8ad9e60  44 bytes
TxIn count: 0; TxOut count: 1
Lock time: 0 (valid anytime)
Inputs:
Output:
Traceback (most recent call last):
  File "/Users/human/.virtualenvs/locktimer/bin/tx", line 9, in <module>
    load_entry_point('pycoin==0.52', 'console_scripts', 'tx')()
  File "/Users/human/.virtualenvs/locktimer/lib/python2.7/site-packages/pycoin/scripts/tx.py", line 438, in main
    dump_tx(tx, args.network)
  File "/Users/human/.virtualenvs/locktimer/lib/python2.7/site-packages/pycoin/scripts/tx.py", line 77, in dump_tx
    address = tx_out.bitcoin_address(netcode=netcode) or "(unknown)"
  File "/Users/human/.virtualenvs/locktimer/lib/python2.7/site-packages/pycoin/tx/TxOut.py", line 60, in bitcoin_address
    info = script_obj_from_script(self.script).info(netcode=netcode)
  File "/Users/human/.virtualenvs/locktimer/lib/python2.7/site-packages/pycoin/tx/pay_to/ScriptPayToAddress.py", line 67, in info
    address = encoding.hash160_sec_to_bitcoin_address(self.hash160, address_prefix=address_prefix)
  File "/Users/human/.virtualenvs/locktimer/lib/python2.7/site-packages/pycoin/encoding.py", line 264, in hash160_sec_to_bitcoin_address
    return b2a_hashed_base58(address_prefix + hash160_sec)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by richardkiss** [comment]
This should work now as of 6971a3bf78a06bad37e519d4434e05073a0fb312.
